<?xml version="1.0" encoding="utf-8"?><Database Name="BCYuks" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-79P1SV36;Initial Catalog=BCYuks;Integrated Security=True;Trust Server Certificate=True" SettingsObjectName="Project___BcYuk.Properties.Settings" SettingsPropertyName="BCYuksConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Cart" Member="Carts">
    <Type Name="Cart">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="UserAuth_Cart" Member="UserAuth" ThisKey="UserID" OtherKey="ID" Type="UserAuth" IsForeignKey="true" />
      <Association Name="Product_Cart" Member="Product" ThisKey="ProductID" OtherKey="ID" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserAuth" Member="UserAuths">
    <Type Name="UserAuth">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Role" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ClassId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="UserAuth_Cart" Member="Carts" ThisKey="ID" OtherKey="UserID" Type="Cart" />
      <Association Name="Class_UserAuth" Member="Class" ThisKey="ClassId" OtherKey="ID" Type="Class" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Category" Member="Categories">
    <Type Name="Category">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="Category_Product" Member="Products" ThisKey="ID" OtherKey="CategoryID" Type="Product" />
      <Association Name="Category_SalesReport" Member="SalesReports" ThisKey="ID" OtherKey="CategoryID" Type="SalesReport" />
    </Type>
  </Table>
  <Table Name="dbo.Class" Member="Classes">
    <Type Name="Class">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ClassName" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="Class_UserAuth" Member="UserAuths" ThisKey="ID" OtherKey="ClassId" Type="UserAuth" />
      <Association Name="Class_Class" Member="Class2" ThisKey="ID" OtherKey="ID" Type="Class" Cardinality="One" />
      <Association Name="Class_Class" Member="Class1" ThisKey="ID" OtherKey="ID" Type="Class" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Order]" Member="Orders">
    <Type Name="Order">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OrderDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TotalPrice" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="PickupScheduleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StatusId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Order_OrderDetail" Member="OrderDetails" ThisKey="ID" OtherKey="OrderID" Type="OrderDetail" />
      <Association Name="Order_Payment" Member="Payments" ThisKey="ID" OtherKey="OrderID" Type="Payment" />
      <Association Name="Order_Receipt" Member="Receipts" ThisKey="ID" OtherKey="OrderID" Type="Receipt" />
      <Association Name="Status_Order" Member="Status" ThisKey="StatusId" OtherKey="ID" Type="Status" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderDetail" Member="OrderDetails">
    <Type Name="OrderDetail">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubTotal" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="Order_OrderDetail" Member="Order" ThisKey="OrderID" OtherKey="ID" Type="Order" IsForeignKey="true" />
      <Association Name="Product_OrderDetail" Member="Product" ThisKey="ProductID" OtherKey="ID" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Payment" Member="Payments">
    <Type Name="Payment">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PaymentDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="StatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PaymentMethodID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Order_Payment" Member="Order" ThisKey="OrderID" OtherKey="ID" Type="Order" IsForeignKey="true" />
      <Association Name="PaymentMethod_Payment" Member="PaymentMethod" ThisKey="PaymentMethodID" OtherKey="ID" Type="PaymentMethod" IsForeignKey="true" />
      <Association Name="Status_Payment" Member="Status" ThisKey="StatusID" OtherKey="ID" Type="Status" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PaymentMethod" Member="PaymentMethods">
    <Type Name="PaymentMethod">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MethodName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="PaymentMethod_Payment" Member="Payments" ThisKey="ID" OtherKey="PaymentMethodID" Type="Payment" />
    </Type>
  </Table>
  <Table Name="dbo.PickupSchedule" Member="PickupSchedules">
    <Type Name="PickupSchedule">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PickupDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="PickupTime" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="PickupEndTime" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Stock" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ImageURL" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="HPP" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Margin" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Association Name="Product_Cart" Member="Carts" ThisKey="ID" OtherKey="ProductID" Type="Cart" />
      <Association Name="Product_OrderDetail" Member="OrderDetails" ThisKey="ID" OtherKey="ProductID" Type="OrderDetail" />
      <Association Name="Product_SalesReport" Member="SalesReports" ThisKey="ID" OtherKey="ProductID" Type="SalesReport" />
      <Association Name="Category_Product" Member="Category" ThisKey="CategoryID" OtherKey="ID" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Receipt" Member="Receipts">
    <Type Name="Receipt">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalAmount" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="ReceiptDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PaymentMethodId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StatusId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Order_Receipt" Member="Order" ThisKey="OrderID" OtherKey="ID" Type="Order" IsForeignKey="true" />
      <Association Name="Status_Receipt" Member="Status" ThisKey="StatusId" OtherKey="ID" Type="Status" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SalesReport" Member="SalesReports">
    <Type Name="SalesReport">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ReportDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Hpp" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="SellingPrice" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Margin" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="OpeningStock" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sold" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VendorHpp" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="CategoryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PaymentMethodID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReportTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ClosingStock" Type="System.Int32" DbType="Int" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TotalRevenue" Type="System.Decimal" DbType="Decimal(29,2)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Profit" Type="System.Decimal" DbType="Decimal(29,2)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Category_SalesReport" Member="Category" ThisKey="CategoryID" OtherKey="ID" Type="Category" IsForeignKey="true" />
      <Association Name="Product_SalesReport" Member="Product" ThisKey="ProductID" OtherKey="ID" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Status" Member="Status">
    <Type Name="Status">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StatusName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Status_Order" Member="Orders" ThisKey="ID" OtherKey="StatusId" Type="Order" />
      <Association Name="Status_Payment" Member="Payments" ThisKey="ID" OtherKey="StatusID" Type="Payment" />
      <Association Name="Status_Receipt" Member="Receipts" ThisKey="ID" OtherKey="StatusId" Type="Receipt" />
    </Type>
  </Table>
</Database>